name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Runs the pipeline when changes are pushed to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest # Runs on the latest version of Ubuntu

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      # Step 3: Create a new gh-pages branch (if it doesn't exist) and deploy files to it
      - name: Deploy to GitHub Pages
        run: |
          # Create a new orphan branch (no commit history)
          git checkout --orphan gh-pages

          # Add all files to Git (including HTML, CSS, JS, images, etc.)
          git add --all

          # Commit the files
          git commit -m "Deploy site to GitHub Pages"

          # Push the changes to the gh-pages branch
          git push --force origin gh-pages
